const products = [
  { id: 1, image: "/assets/Images/men1.jpeg", title: "ClassyShirt", price: 10000, description: "Elegant and trendy wear for any occasion.", lengthyDes: "This classy shirt is designed for modern elegance, combining a sleek cut with premium fabric that offers comfort and durability. Perfect for both casual outings and formal events, it’s a wardrobe essential for every stylish man." },
  { id: 2, image: "/assets/Images/sneak1.jpeg", title: "BreathSneakers", price: 13000, description: "Comfortable footwear for everyday style.", lengthyDes: "Engineered with breathable mesh and cushioned soles, these sneakers provide all-day comfort and support. Ideal for long walks, workouts, or casual strolls, they’re a versatile choice for active individuals." },
  { id: 3, image: "/assets/Images/bag3.jpeg", title: "UnisexBag", price: 10000, description: "Sleek and versatile for daily use.", lengthyDes: "Designed for functionality and fashion, this unisex bag offers ample storage, secure compartments, and a modern silhouette. It’s the perfect companion for school, work, or travel needs." },
  { id: 4, image: "/assets/Images/watch3.jpeg", title: "BrownWatch", price: 20000, description: "Timeless accessory with a classy touch.", lengthyDes: "Crafted with a genuine leather strap and an elegant brown dial, this wristwatch blends timeless sophistication with everyday practicality. A great accessory for elevating your style effortlessly." },

  { id: 5, image: "/assets/Images/glas.jpeg", title: "Sunshade", price: 8000, description: "Stylish protection for your eyes.", lengthyDes: "These sunshades not only protect your eyes from harmful UV rays but also enhance your overall look with their chic frame and tint. A must-have accessory for sunny days." },
  { id: 6, image: "/assets/Images/skirt.jpeg", title: "AnkaraSkirt", price: 9000, description: "Feminine and flattering fit.", lengthyDes: "This Ankara skirt showcases vibrant African prints and a flattering silhouette, making it perfect for both traditional ceremonies and casual wear. Its high-quality fabric ensures comfort and longevity." },
  { id: 7, image: "/assets/Images/jewel.jpeg", title: "BridalJewels", price: 16000, description: "Elegant sparkle for your outfit.", lengthyDes: "Crafted for the bride or celebrant, this bridal jewel set includes a necklace, earrings, and bracelet—all designed with precision stones to add sparkle and sophistication to your look." },
  { id: 8, image: "/assets/Images/sun.jpeg", title: "FloralDress", price: 16000, description: "Breezy and fashionable pick.", lengthyDes: "This floral sundress is your go-to for warm days. With its flowy material and beautiful floral patterns, it brings a fresh, breezy feel that’s ideal for beach outings or picnics." },

  { id: 9, image: "/assets/Images/sunhat.jpeg", title: "SunHat", price: 6000, description: "Classic top-off for your outfit.", lengthyDes: "This wide-brim sun hat is crafted for both style and protection, shielding your face while adding flair to your look. Great for beach days, vacations, and summer events." },
  { id: 10, image: "/assets/Images/trous.jpeg", title: "ClassyPant", price: 10000, description: "Casual and fitted for all-day wear.", lengthyDes: "These pants are tailored to deliver a smart yet relaxed look. Made from soft, breathable fabric, they’re suitable for business casual settings and weekend outings alike." },
  { id: 11, image: "/assets/Images/men.jpeg", title: "StyleShirt", price: 45000, description: "Refined and bold for modern men.", lengthyDes: "The StyleShirt combines bold design with premium texture, ideal for men who appreciate a clean, fashion-forward aesthetic. Elevate your everyday style with this versatile piece." },
  { id: 12, image: "/assets/Images/sneak2.jpeg", title: "ChicSneakers", price: 14000, description: "Trendy kicks with a sleek edge.", lengthyDes: "Designed with a modern silhouette and quality materials, these sneakers deliver both trend and comfort. Perfect for streetwear lovers and minimal fashion enthusiasts." },

  { id: 13, image: "/assets/Images/men2.jpeg", title: "AnkaraShirt", price: 12000, description: "Cultural flair meets comfort.", lengthyDes: "This Ankara shirt offers a fresh blend of culture and comfort, featuring bold prints and breathable cotton that feels as good as it looks. Pair with jeans or trousers for a standout fit." },
  { id: 14, image: "/assets/Images/men3.jpeg", title: "StripedShirt", price: 15000, description: "Sharp lines for confident looks.", lengthyDes: "Crisp stripes meet tailored comfort in this shirt that’s ideal for work, events, or casual outings. Its striking pattern is matched with a fit that flatters all builds." },
  { id: 15, image: "/assets/Images/men4.jpeg", title: "UnisexShirt", price: 10000, description: "Universal style that fits all.", lengthyDes: "This shirt’s neutral design makes it a favorite for all genders. Its breathable fabric and simple elegance make it a daily wear essential with elevated charm." },
  { id: 16, image: "/assets/Images/sneak3.jpeg", title: "CasualSneakers", price: 15000, description: "Effortless comfort and style.", lengthyDes: "Built for the go-getter, these casual sneakers provide excellent foot support with a lightweight feel. The neutral colorway means they pair well with almost anything." },

  { id: 17, image: "/assets/Images/sneak4.jpeg", title: "FreshSneakers", price: 20000, description: "Bold steps with fresh flair.", lengthyDes: "Step into freshness with these bold sneakers designed for impact. Featuring eye-catching colors and superior traction, they’re the perfect blend of fashion and function." },
  { id: 18, image: "/assets/Images/baga.jpeg", title: "WineBag", price: 20000, description: "Rich tone for elegant storage.", lengthyDes: "The deep wine color adds a premium touch to this leather bag, which is perfect for storing your daily essentials in an organized, classy manner." },
  { id: 19, image: "/assets/Images/bag1.jpeg", title: "ToteBag", price: 18000, description: "Roomy and durable for everyday use.", lengthyDes: "This tote bag offers spacious compartments, strong handles, and durable material, making it ideal for shopping, travel, or everyday errands." },
  { id: 20, image: "/assets/Images/watch1.jpeg", title: "GoldWatch", price: 200000, description: "Luxury timepiece that shines.", lengthyDes: "Precision craftsmanship meets luxury in this gold watch, perfect for making a statement at high-end events or as a premium gift for a loved one." },

  { id: 21, image: "/assets/Images/bag2.jpeg", title: "LaptopBag", price: 20000, description: "Functional with a professional edge.", lengthyDes: "Keep your devices safe and stylish with this professional-grade laptop bag. It features padded compartments, multiple zippers, and a water-resistant finish." },
  { id: 22, image: "/assets/Images/glass.jpeg", title: "ReadGlasses", price: 12000, description: "Clarity and fashion in one frame.", lengthyDes: "Designed to complement both vision and fashion needs, these glasses feature a lightweight frame and anti-glare lenses for optimal reading comfort." },
  { id: 23, image: "/assets/Images/bridal.jpeg", title: "BridalHat", price: 6000, description: "Graceful topper for special days.", lengthyDes: "This delicate bridal hat completes your wedding outfit with a soft, romantic touch. Its floral trim and secure fit make it ideal for photos and ceremonies alike." },
  { id: 24, image: "/assets/Images/pantrou.jpeg", title: "CasualPant", price: 8000, description: "Relaxed fit for laid-back vibes.", lengthyDes: "With an easygoing cut and breathable fabric, these casual pants are made for weekend relaxation and off-duty comfort. Pair with tees or polos for a chill vibe." },

  { id: 25, image: "/assets/Images/glasss.jpeg", title: "BlueBlock", price: 6000, description: "Protect your eyes in style.", lengthyDes: "Reduce eye strain in style with these blue light-blocking glasses. Great for screen-heavy days, they combine tech-savvy protection with a sleek design." },
  { id: 26, image: "/assets/Images/skirt1.jpeg", title: "PencilSkirt", price: 6000, description: "Streamlined fit with elegance.", lengthyDes: "This pencil skirt accentuates your silhouette with its tailored fit and soft fabric. Perfect for the office or evening engagements." },
  { id: 27, image: "/assets/Images/skirt2.jpeg", title: "FloralSkirt", price: 16000, description: "Fresh blossoms in every step.", lengthyDes: "Bring a touch of spring with you year-round in this floral skirt. The light fabric and bold prints make it a standout addition to any wardrobe." },
  { id: 28, image: "/assets/Images/jewel1.jpeg", title: "SilverSet", price: 10000, description: "Shimmering accents for your look.", lengthyDes: "The SilverSet includes coordinated pieces that elevate any ensemble. With its polished finish and fine detailing, it’s both classic and contemporary." },

  { id: 29, image: "/assets/Images/jewel2.jpeg", title: "KnuckleRings", price: 5000, description: "Edgy detail with modern flair.", lengthyDes: "These knuckle rings come in various designs to layer or wear solo. Perfect for expressing your unique personality with an edgy twist." },
  { id: 30, image: "/assets/Images/jewel3.jpeg", title: "ClassyJewels", price: 106000, description: "Sophisticated touch to your attire.", lengthyDes: "Designed with the highest craftsmanship, this premium jewelry set exudes class and luxury—perfect for formal events and upscale gifting." },
  { id: 31, image: "/assets/Images/sund.jpeg", title: "SleeveDress", price: 14000, description: "Airy and graceful for sunny days.", lengthyDes: "This sleeveless dress offers flowing lines and breathable fabric for staying cool in style. Ideal for garden parties or casual brunches." },
  { id: 32, image: "/assets/Images/sundr.jpeg", title: "VneckDress", price: 9000, description: "Vibrant neckline with chic charm.", lengthyDes: "Featuring a v-neckline and soft pleats, this dress provides a flattering fit for all body types. Pair it with sandals or heels to complete the look." },

  { id: 33, image: "/assets/Images/sundre.jpeg", title: "NavyDress", price: 25000, description: "Bold yet serene in deep blue.", lengthyDes: "This navy blue dress balances elegance and calm, offering a structured fit with flowy elegance. Ideal for dinner dates or business functions." },
  { id: 34, image: "/assets/Images/face.jpeg", title: "FaceCap", price: 4500, description: "Cool and casual for sunny days.", lengthyDes: "This face cap adds a sporty touch to any outfit while keeping you shaded. Adjustable and breathable, it’s a go-to for sunny adventures." },
  { id: 35, image: "/assets/Images/fauxfur.jpeg", title: "FurHat", price: 8000, description: "Soft warmth with a stylish edge.", lengthyDes: "Lined with faux fur, this hat is cozy yet chic—perfect for winter outfits and fashionable layering." },
  { id: 36, image: "/assets/Images/bridal.jpeg", title: "BridalHat", price: 6000, description: "Elegant finish for wedding charm.", lengthyDes: "A repeat bestseller, this bridal hat features floral lace and satin ribbon for the perfect blend of elegance and comfort." },

  { id: 37, image: "/assets/Images/side.jpeg", title: "StripePant", price: 12000, description: "Sporty stripes meet urban trend.", lengthyDes: "These pants mix athletic appeal with fashion-forward cuts. Ideal for street style lovers and comfort seekers alike." },
  { id: 38, image: "/assets/Images/pantrou.jpeg", title: "CasualPant", price: 8000, description: "Relaxed fit for laid-back vibes.", lengthyDes: "Another favorite for easy wear, this pant delivers unmatched comfort with subtle tailoring that suits all-day lounging or errands." }
];

export default products
